entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: limpopo113@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: regru
        delayBeforeCheck: 0

# Включить Docker-провайдер (если Traefik управляет контейнерами)
providers:
  docker:
    exposedByDefault: false  # Только контейнеры с `traefik.enable=true` будут обрабатываться
