version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ../data:/app/../data
    command: python watcher.py
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8

